import { expect, test } from "@playwright/test";

test("promociones admite varios productos o una marca o categoría", async ({ page }) => {
  await page.goto("/tienda/ingresar");
  await expect(async () => {
    await page.getByRole("button", { name: "Administración", exact: true }).click();
    expect(await page.getByLabel("Correo electrónico").inputValue()).toBe("admin@districo.com");
  }).toPass({ timeout: 10000 });
  await page.getByRole("button", { name: "Ingresar", exact: true }).click();
  await expect(page).toHaveURL(/\/tienda$/, { timeout: 10000 });
  await page.goto("/tienda/admin/promociones");
  await expect(page.getByRole("button", { name: "Crear regla cruzada" })).toBeVisible();
  await page.getByRole("button", { name: "Crear promoción" }).click();
  const dialog = page.getByRole("dialog", { name: "Crear promoción" });
  await dialog.getByRole("textbox", { name: "Nombre *" }).fill("Selección de prueba");
  await dialog.getByRole("checkbox", { name: "Requiere compra para activar" }).uncheck();
  await expect(dialog.locator(".promotion-options label").nth(1)).toBeVisible();
  await dialog.locator(".promotion-options label").nth(0).getByRole("checkbox").check();
  await dialog.locator(".promotion-options label").nth(1).getByRole("checkbox").check();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(dialog).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 800 });
  await dialog.getByRole("spinbutton", { name: "Porcentaje *" }).fill("12");
  await dialog.getByRole("button", { name: "Guardar promoción" }).click();
  await expect(dialog).not.toBeVisible();
  const card = page.locator(".admin-cards .card").filter({ hasText: "Selección de prueba" });
  await expect(card).toContainText("2 productos");
  await card.getByRole("button", { name: "Editar" }).click();
  const editDialog = page.getByRole("dialog", { name: "Editar promoción" });
  await editDialog.getByRole("radio", { name: "Marcas" }).check();
  await expect(editDialog.locator(".promotion-options label").first()).toBeVisible();
  await editDialog.locator(".promotion-options label").first().getByRole("checkbox").check();
  await editDialog.getByRole("radio", { name: "Categorías" }).check();
  await expect(editDialog.locator(".promotion-options label").first()).toBeVisible();
  await editDialog.locator(".promotion-options label").first().getByRole("checkbox").check();
  await editDialog.getByRole("button", { name: "Guardar promoción" }).click();
  await expect(card).toContainText("1 categoría");
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("districo-demo-v1") ?? "{}"));
  const promotion = saved.promotions.find((item: { name: string }) => item.name === "Selección de prueba");
  expect(promotion.rewards).toHaveLength(1);
  expect(promotion.rewards[0].targetType).toBe("CATEGORY");
});

test("promoción con activadores y destinos múltiples conserva ambas selecciones al editar", async ({ page }, testInfo) => {
  test.setTimeout(60000);
  await page.goto("/tienda/ingresar");
  await expect(async () => {
    await page.getByRole("button", { name: "Administración", exact: true }).click();
    expect(await page.getByLabel("Correo electrónico").inputValue()).toBe("admin@districo.com");
  }).toPass({ timeout: 10000 });
  await page.getByRole("button", { name: "Ingresar", exact: true }).click();
  await expect(page).toHaveURL(/\/tienda$/, { timeout: 10000 });
  await page.goto("/tienda/admin/promociones");
  await page.evaluate(() => {
    const state = JSON.parse(localStorage.getItem("districo-demo-v1")!);
    const example = state.products[0];
    for (let index = 0; index < 25; index++) state.products.push({ ...example, brand: null, id: `qa-promo-product-${index}`, slug: `qa-promo-product-${index}`, name: `QA producto ${index}`, variants: [{ ...example.variants[0], id: `qa-promo-variant-${index}`, sku: `QA-P-${index}` }] });
    localStorage.setItem("districo-demo-v1", JSON.stringify(state));
  });
  await page.reload();
  await page.getByRole("button", { name: "Crear promoción", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Crear promoción" });
  await dialog.getByRole("textbox", { name: "Nombre *" }).fill("Cruce múltiple");
  const trigger = dialog.getByRole("group", { name: "Se activa al comprar *", exact: true });
  const target = dialog.getByRole("group", { name: "Aplicar promoción a *", exact: true });
  await expect(trigger.locator(".promotion-options label").nth(1)).toBeVisible();
  await trigger.locator(".promotion-options label").nth(0).getByRole("checkbox").check();
  await trigger.locator(".promotion-options label").nth(1).getByRole("checkbox").check();
  await trigger.getByRole("button", { name: "Página siguiente" }).click();
  await expect(trigger.getByText("2 /", { exact: false })).toBeVisible();
  await expect(trigger.locator(".promotion-selected span")).toHaveCount(2);
  await target.getByRole("radio", { name: "Marcas", exact: true }).check();
  await expect(target.locator(".promotion-options label").nth(1)).toBeVisible();
  await target.locator(".promotion-options label").nth(0).getByRole("checkbox").check();
  await target.locator(".promotion-options label").nth(1).getByRole("checkbox").check();
  await dialog.getByRole("spinbutton", { name: "Porcentaje *", exact: true }).fill("15");
  await dialog.getByRole("spinbutton", { name: "Cantidad mínima *", exact: true }).fill("2");
  await dialog.getByLabel("Finaliza", { exact: true }).fill("2026-12-31");
  await dialog.evaluate((node) => { node.scrollTop = 0; });
  await page.screenshot({ path: testInfo.outputPath("promotion-scopes-desktop.png"), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await dialog.evaluate((node) => { node.scrollTop = 0; });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("promotion-scopes-mobile.png"), fullPage: true });
  await page.setViewportSize({ width: 1280, height: 800 });
  await dialog.getByRole("button", { name: "Guardar promoción" }).click();
  await expect(dialog).not.toBeVisible();
  const card = page.locator(".admin-cards .card").filter({ hasText: "Cruce múltiple" });
  await expect(card).toContainText("Se activa al comprar:");
  await expect(card).toContainText("2 marcas");
  await expect(card).toContainText("Cantidad mínima: 2");
  await card.getByRole("button", { name: "Editar", exact: true }).click();
  const edit = page.getByRole("dialog", { name: "Editar promoción" });
  const editTrigger = edit.getByRole("group", { name: "Se activa al comprar *", exact: true });
  const editTarget = edit.getByRole("group", { name: "Aplicar promoción a *", exact: true });
  await expect(editTrigger.locator(".promotion-selected span")).toHaveCount(2);
  await expect(editTarget.locator(".promotion-selected span")).toHaveCount(2);
  await expect(edit.getByLabel("Finaliza", { exact: true })).toHaveValue("2026-12-31");
  await editTrigger.getByRole("radio", { name: "Categorías", exact: true }).check();
  await expect(editTrigger.locator(".promotion-options label").nth(1)).toBeVisible();
  await editTrigger.locator(".promotion-options label").nth(0).getByRole("checkbox").check();
  await editTrigger.locator(".promotion-options label").nth(1).getByRole("checkbox").check();
  await editTarget.getByRole("radio", { name: "Productos", exact: true }).check();
  await expect(editTarget.locator(".promotion-options label").nth(1)).toBeVisible();
  await editTarget.locator(".promotion-options label").nth(0).getByRole("checkbox").check();
  await editTarget.locator(".promotion-options label").nth(1).getByRole("checkbox").check();
  await edit.getByRole("combobox", { name: "Condición de activación", exact: true }).selectOption("MIN_AMOUNT");
  await edit.getByRole("spinbutton", { name: "Importe mínimo de la selección *" }).fill("500");
  await edit.getByRole("button", { name: "Guardar promoción" }).click();
  await expect(edit).not.toBeVisible();
  await page.reload();
  await expect(card).toContainText("2 productos");
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem("districo-demo-v1")!).promotions.find((item: { name: string }) => item.name === "Cruce múltiple"));
  expect(saved.conditions).toHaveLength(1);
  expect(saved.conditions[0].targetType).toBe("CATEGORY");
  expect(saved.conditions[0].targetIds).toHaveLength(2);
  expect(saved.conditions[0].metric).toBe("MIN_AMOUNT");
  expect(saved.conditions[0].minAmount).toBe(500);
  expect(saved.rewards).toHaveLength(2);
  expect(saved.rewards[0].targetType).toBe("PRODUCT");
});
