-- Prepared only: review the server role before applying this migration.
-- No policies grant anonymous/authenticated Data API access.
-- The migration owner/server role retains access; Supabase auth/storage are untouched.
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserPermission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RefreshToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Brand" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Laboratory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductVariant" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceList" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Price" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PriceHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CartItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockReservation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerDocument" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Promotion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromotionCondition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromotionReward" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExpirationPromotion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecommendationRuleProduct" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttributeDefinition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AttributeValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductAttributeValue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductMedia" ENABLE ROW LEVEL SECURITY;
